# Generated by Django 4.1.3 on 2022-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du produit"
                    ),
                ),
                (
                    "brands",
                    models.CharField(max_length=100, verbose_name="Marques du produit"),
                ),
                ("link", models.URLField(unique=True)),
                ("nutriscore", models.CharField(max_length=1)),
                ("image", models.URLField()),
                ("fat", models.FloatField()),
                ("saturated_fat", models.FloatField()),
                ("sugars", models.FloatField()),
                ("salt", models.FloatField()),
            ],
        ),
    ]
