# Generated by Django 4.1.3 on 2022-11-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="brands",
        ),
        migrations.RemoveField(
            model_name="products",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.RemoveField(
            model_name="products",
            name="link",
        ),
        migrations.RemoveField(
            model_name="products",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="products",
            name="saturated_fat",
        ),
        migrations.RemoveField(
            model_name="products",
            name="sugars",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
