# Generated by Django 4.1.3 on 2022-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_products_brands_remove_products_fat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
