# Generated by Django 4.1.3 on 2022-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_products_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="category",
            new_name="details",
        ),
        migrations.AddField(
            model_name="products",
            name="link",
            field=models.URLField(default="", unique=True),
            preserve_default=False,
        ),
    ]
