# Generated by Django 4.1.3 on 2022-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_products_brands_products_fat_products_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="fat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="salt",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="saturated_fat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="sugars",
            field=models.FloatField(null=True),
        ),
    ]
