# Generated by Django 4.1.3 on 2022-11-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_products_fat_alter_products_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="products",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="products",
            name="saturated_fat",
        ),
        migrations.RemoveField(
            model_name="products",
            name="sugars",
        ),
    ]
