# Generated by Django 4.1.3 on 2022-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_category_products_details_products_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
