# Generated by Django 4.1.3 on 2022-11-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_products_fat_remove_products_salt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.RemoveField(
            model_name="products",
            name="link",
        ),
    ]
