# Generated by Django 4.1.3 on 2022-11-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_products_image_remove_products_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="brands",
        ),
    ]
