# Generated by Django 4.1.3 on 2022-11-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_products_prod_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="categories", to="product.products"
                    ),
                ),
            ],
        ),
    ]
