# Generated by Django 4.1.3 on 2022-11-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="products",
        ),
    ]
