# Generated by Django 4.1.3 on 2022-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_products_brands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(max_length=1000),
        ),
    ]
