# Generated by Django 4.1.3 on 2022-11-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_category_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
