# Generated by Django 4.1.3 on 2022-11-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0010_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="prod",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="sub",
        ),
        migrations.AddField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produit",
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favorite",
            name="substitute",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute",
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="product.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="prod_store",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="CategoryProduct",
        ),
    ]
