# Generated by Django 4.1.3 on 2022-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
    ]
