# Generated by Django 4.1.3 on 2022-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="second_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="Last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
