# Generated by Django 4.1.3 on 2022-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_remove_customuser_second_name_customuser_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
