# Generated by Django 4.1.3 on 2022-11-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_customuser_is_active_customuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
