# Generated by Django 4.1.3 on 2022-11-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_remove_customuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="Last_name",
            new_name="last_name",
        ),
    ]
