# Generated by Django 4.1.3 on 2022-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_rename_last_name_customuser_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="second_name",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
