# Generated by Django 4.1.3 on 2022-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0018_alter_customuser_options_remove_customuser_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_large",
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image_small",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
