# Generated by Django 4.1.3 on 2022-12-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_alter_product_image_large_alter_product_image_small"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("code", models.TextField()),
                ("details", models.TextField()),
                ("link", models.URLField(null=True)),
                ("image_large", models.TextField(null=True)),
                ("image_small", models.TextField(null=True)),
                ("prod_store", models.CharField(max_length=1500, null=True)),
                ("nutriscore", models.CharField(max_length=1)),
                ("category", models.TextField(null=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produit",
                to="product.products",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="substitute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitute",
                to="product.products",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
