# Generated by Django 4.1.3 on 2022-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_alter_products_nutriscore_alter_products_prod_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="nutriscore",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="prod_store",
            field=models.TextField(null=True),
        ),
    ]
