# Generated by Django 4.1.3 on 2022-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ManyToManyField(to="product.categories"),
        ),
    ]
