# Generated by Django 4.1.3 on 2022-12-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_remove_products_category_products_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="code",
        ),
    ]
