# Generated by Django 4.1.3 on 2022-12-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0026_remove_products_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="name",
            new_name="category",
        ),
    ]
