# Generated by Django 4.1.3 on 2022-12-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0028_remove_products_category_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.TextField(null=True),
        ),
    ]
