# Generated by Django 4.1.3 on 2022-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0030_alter_products_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="large_image_nutricore",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="small_image_nutricore",
            field=models.TextField(null=True),
        ),
    ]
