# Generated by Django 4.1.3 on 2022-12-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0031_products_large_image_nutricore_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="large_image_nutricore",
        ),
        migrations.RemoveField(
            model_name="products",
            name="small_image_nutricore",
        ),
    ]
