# Generated by Django 4.1.3 on 2022-12-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_remove_products_large_image_nutricore_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="second_name",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
