language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="nutella.settings"

services:
  - postgresql

script:
  - python manage.py test nutella/product/tests/test_units

# safelist
branches:
  only:
    - master
