language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="nutella.settings"

services:
  - postgresql

script:
  - ./manage.py test

# safelist
branches:
  only:
    - master
